disabled = false
languageCode = "en"
languageName = "English"
weight = 1
title = "Blowfish"

[params]
displayName = "EN"
isoCode = "en"
rtl = false
dateFormat = "2 January 2006"

    [params.author]
    name = "Rikke"
    image = ""
    email = "cph-rm225@stud.ek.dk"
    headline = "Student at EK"
    links = []